apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: myspace # {"$kpt-set":"namespace"}
  name: storage-deployment
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: storage
        image: storage:1.7.7
